#!/usr/bin/env python3
import gnupg
import base64
import json
import pprint

from boto3.session import Session

def decrypt_value(gpg, enc_value):
    enc_data = base64.b64decode(enc_value)
    return gpg.decrypt(enc_data)


def get_module(state, module_name="root"):
    for module in state["modules"]:
        if "/".join(module["path"]) == module_name:
            return module


def get_output(state, module, key):
    module = get_module(state, module)
    return module["outputs"][key]["value"]


def main():
    gpg = gnupg.GPG()

    path = "./terraform.tfstate"
    with open(path) as handle:
        state = json.load(handle)

    password = decrypt_value(gpg, get_output(state, "root", "kelledge_password"))
    access_key_id = get_output(state, "root", "kelledge_access_key_id")
    access_key_secret = decrypt_value(gpg, get_output(state, "root", "kelledge_access_key_secret"))

    print(password)
    print(access_key_id)
    print(access_key_secret)


if __name__ == '__main__':
    main()
