- hosts: bastion
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: "../bastion/id_rsa"
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
  - name: Install dependencies
    apt:
      name: python3-psycopg2

  - name: Add kelledge role
    postgresql_user:
      db: cidb
      name: kelledge
      password: simplepassword
      priv: 'ALL'
      # role_attr_flags: "SUPERUSER"
      login_host: ci-database.cbl4l1zwnvtl.us-east-1.rds.amazonaws.com
      port: 5432
      login_user: root_user
      login_password: v6otpxUgDjX49s01aUCB
      state: present
